In [1]:
import numpy as np
import random
from Encoder import Encoder

### Example Usage

In [2]:
base_matrix_path = 'base_matrices/NR_1_1_48.txt'
expansion_factor = 12
en = Encoder(base_matrix_path,expansion_factor)

# generating codeword for a random message vector
msg = en.generate_random_message()
codeword = en.encode(msg)
print("message :\n",msg)
print("codeword :\n",codeword)

message :
 [1 1 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0
 0 0 1 1 0 0 0 0 1 1 0 1 0 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 1
 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0
 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 1
 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1
 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1
 1 1 0 0 1 1 1 1 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 1
 1 0 1 0 0]
codeword :
 [1 1 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0
 0 0 1 1 0 0 0 0 1 1 0 1 0 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 1
 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0
 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 1
 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1
 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 

In [3]:
H = en.get_parity_check_matrix()
print("Parity Check Matrix : \n",H)

Parity Check Matrix : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
