In [1]:
import numpy as np
import math
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import qr
import itertools
from scipy.special import erfc
import galois
# from MI_Dec import MI_Dec
from Residual_Dec import Residual_Dec
from Dec import Dec

In [2]:
# generates list of codewords corresponding to the parity check matrix H
def get_codewords(H):
    GF = galois.GF(2)
    A = GF(H)
    N = A.null_space()
    vec = [np.array(v) for v in itertools.product([0, 1], repeat=N.shape[0])]
    C = np.array(GF(vec) @ N)
    return C


def circular_shift_identity(z, k):
    if k == -1:
        return np.zeros((z, z), dtype=int)
    else:
        return np.roll(np.eye(z, dtype=int), -k, axis=1)

def expand_base_matrix(B, z):
    m, n = B.shape
    H = np.zeros((m * z, n * z), dtype=int)  # Full parity check matrix initialized to zeros
    for i in range(m):
        for j in range(n):
            # Expand each base matrix element into a z x z block
            block = circular_shift_identity(z, B[i, j])
            H[i * z:(i + 1) * z, j * z:(j + 1) * z] = block
    return H


In [3]:
# B = np.array([[0,2,-1,3,-1,-1,2,4,1,0],
#             [3,1,-1,-1,0,0,1,2,3,0],
#             [1,0,0,-1,1,4,2,1,0,-1],
#             [-1,0,0,2,3,-1,-1,-1,0,-1],
#             [1,0,2,0,1,0,-1,-1,-1,-1],
#             [2,1,0,0,2,-1,-1,-1,1,-1]]
#             ,dtype=int)
# print("B = \n",B)
# z = 5
# H = expand_base_matrix(B,z)

H = np.array( [[0,0,1,1,0,0,1,0,0,0,0,0,0,0,0]
,[1,0,0,0,1,0,0,1,0,0,0,0,0,0,0]
,[0,1,0,0,0,1,0,0,1,0,0,0,0,0,0]
,[1,0,0,0,0,1,1,0,0,0,0,0,0,0,0]
,[0,1,0,1,0,0,0,1,0,0,0,0,0,0,0]
,[0,0,1,0,1,0,0,0,1,0,0,0,0,0,0]
,[1,0,0,1,0,0,0,0,1,0,0,0,0,0,0]
,[0,1,0,0,1,0,1,0,0,0,0,0,0,0,0]
,[0,0,1,0,0,1,0,1,0,0,0,0,0,0,0]
,[1,0,0,1,0,0,1,0,0,1,0,0,1,0,0]
,[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0]
,[0,0,1,0,0,1,0,0,1,0,0,1,0,0,1]],dtype=int)
n = H.shape[1]



print("H : \n",H)

C = get_codewords(H)
print("Codewords : \n",C)
print(len(C)," codewords found")
dmin = np.min(np.sum(C[1:],axis=1))
print("dmin = ",dmin)



H : 
 [[0 0 1 1 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1 0 0 1 0 0 1]]
Codewords : 
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 1 0 0 1 0 0 1]
 [0 0 0 1 1 1 1 1 1 0 1 0 0 1 0]
 [0 0 0 1 1 1 1 1 1 0 1 1 0 1 1]
 [0 0 0 1 1 1 1 1 1 1 0 0 1 0 0]
 [0 0 0 1 1 1 1 1 1 1 0 1 1 0 1]
 [0 0 0 1 1 1 1 1 1 1 1 0 1 1 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 1 1 1 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 1 1 0 

In [4]:
def getBER_residual(snr,H,C,num_iter,N):
    # this is for awgn, similarly do for others too
    avg = 0
    tg = Residual_Dec(H,"bsc",0,num_iter,1)
    
    for i in range(N):
        c = C[np.random.choice(len(C))]
        sigma = 1/math.sqrt(snr)
        y = np.power(-1,c) + np.random.normal(loc=0, scale=sigma, size=c.shape)
        c_hat = tg.decode(y)
        c_hat = [1 if val else 0 for val in c_hat]
        c_hat = np.array(c_hat)%2
        e = np.sum((c_hat+c)%2)/len(c)
        avg = avg + e
    
    return avg/N


In [37]:
num_iter = 100
snr = 1.2
sigma = 1/math.sqrt(snr)

dec = Residual_Dec(H=H,channel_model="bsc",channel_parameters=0,num_iter=num_iter,cluster_size=1)
# dec = Dec(H=H,channel_model="bsc",channel_parameters=0,num_iter=num_iter,cluster_size=1)

In [38]:
c = C[np.random.choice(len(C))]
print(f"codeword = {c}")
y = np.power(-1,c) + np.random.normal(loc=0, scale=sigma, size=c.shape)
print(f"recieved codeword = {np.round(y,2)}")
c_hat = dec.decode(y)
print(f"Decoded codeword = {c_hat}")
e = (c+c_hat)%2
print(f"Error vector = {e}")

codeword = [0 0 0 1 1 1 1 1 1 0 1 0 0 1 0]
recieved codeword = [ 0.55  0.58  1.15 -0.96 -0.99 -0.79 -1.65 -0.35  0.89  0.98 -0.81  1.34
  2.11 -1.56  1.82]
Decoded codeword = [0 0 0 0 1 1 0 0 0 0 1 0 0 1 0]
Error vector = [0 0 0 1 0 0 1 1 1 0 0 0 0 0 0]


In [48]:
print("BERs for residual-scheduling\n-----------------\n")
snrdb_vals = [0.1, 0.2, 0.35, 0.5, 0.9, 1.5, 2.2, 3, 3.7, 4.3, 4.9]
bers_residual = []
N = 1000
for snrdb in snrdb_vals:
    snr = math.pow(10,snrdb/20)
    ber = getBER_residual(snr,H,C,100,N)
    bers_residual.append(ber)
    print(f"BER = {ber}\t\t\t SNR(db) = {snrdb}")
#     snrdb_vals.append(snrdb)

In [ ]:
bers_round_robin = 
 [0.05097999999999882, 0.050506666666665465, 0.04701999999999893, 0.047526666666665565, 0.04320666666666572, 0.036659999999999346, 0.03204666666666622, 0.026526666666666473, 0.020719999999999947, 0.017320000000000068, 0.01510000000000014]
bers_flooding =  
 [0.10109333333334035, 0.10088666666667416, 0.09908000000000743, 0.09604000000000677, 0.08928666666667322, 0.0784600000000042, 0.07056666666666958, 0.05982666666666724, 0.051219999999998114, 0.046546666666665015, 0.03915333333333203]


In [ ]:
plt.plot(snrdb_vals, bers_round_robin, 'o')  
plt.plot(snrdb_vals, bers_round_robin, '--',label="Round Robin")
plt.plot(snrdb_vals, bers_flooding, 'o')  
plt.plot(snrdb_vals, bers_flooding, '--',label="Flooding")
plt.plot(snrdb_vals, bers_residual, 'o')  
plt.plot(snrdb_vals, bers_residual, '--',label="Residual")


plt.title("BER vs SNR Plot")
plt.ylabel("BER")
plt.xlabel("SNR (in dB)")
plt.legend()
plt.yscale('log')
plt.grid(True, which="both", ls="--")
plt.show()
